language = "zh"

[display]
mode = "quiet"

thinking_messages = false

tool_messages = false

[log]
level = "info"

[[projects]]
name = "小克"

[projects.agent]
type = "claudecode"

[projects.agent.options]
work_dir = "e:\\better\\EmotionalAgent"
mode = "default"

[[projects.platforms]]
type = "weixin"

[projects.platforms.options]
# token = "通过 cc-connect weixin setup --project 小克 自动获取"
# allow_from = ""  # 建议填写以限制使用者
token = "fb6783d6663d@im.bot:060000ea3ad35cc2a71231ba02dfd63ebe9842"
base_url = "https://ilinkai.weixin.qq.com"
account_id = "fb6783d6663d@im.bot"
